/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelEncarregadoRouteImport } from './routes/painel.$encarregado'
import { Route as PainelEncarregadoIndexRouteImport } from './routes/painel.$encarregado.index'
import { Route as PainelEncarregadoAnoMesDiaRouteImport } from './routes/painel.$encarregado.$anoMes.$dia'

const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEncarregadoRoute = PainelEncarregadoRouteImport.update({
  id: '/$encarregado',
  path: '/$encarregado',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEncarregadoIndexRoute = PainelEncarregadoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelEncarregadoRoute,
} as any)
const PainelEncarregadoAnoMesDiaRoute =
  PainelEncarregadoAnoMesDiaRouteImport.update({
    id: '/$anoMes/$dia',
    path: '/$anoMes/$dia',
    getParentRoute: () => PainelEncarregadoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/$encarregado': typeof PainelEncarregadoRouteWithChildren
  '/painel/': typeof PainelIndexRoute
  '/painel/$encarregado/': typeof PainelEncarregadoIndexRoute
  '/painel/$encarregado/$anoMes/$dia': typeof PainelEncarregadoAnoMesDiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelIndexRoute
  '/painel/$encarregado': typeof PainelEncarregadoIndexRoute
  '/painel/$encarregado/$anoMes/$dia': typeof PainelEncarregadoAnoMesDiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/painel/$encarregado': typeof PainelEncarregadoRouteWithChildren
  '/painel/': typeof PainelIndexRoute
  '/painel/$encarregado/': typeof PainelEncarregadoIndexRoute
  '/painel/$encarregado/$anoMes/$dia': typeof PainelEncarregadoAnoMesDiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/painel'
    | '/painel/$encarregado'
    | '/painel/'
    | '/painel/$encarregado/'
    | '/painel/$encarregado/$anoMes/$dia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/painel'
    | '/painel/$encarregado'
    | '/painel/$encarregado/$anoMes/$dia'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/painel'
    | '/painel/$encarregado'
    | '/painel/'
    | '/painel/$encarregado/'
    | '/painel/$encarregado/$anoMes/$dia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/$encarregado': {
      id: '/painel/$encarregado'
      path: '/$encarregado'
      fullPath: '/painel/$encarregado'
      preLoaderRoute: typeof PainelEncarregadoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/$encarregado/': {
      id: '/painel/$encarregado/'
      path: '/'
      fullPath: '/painel/$encarregado/'
      preLoaderRoute: typeof PainelEncarregadoIndexRouteImport
      parentRoute: typeof PainelEncarregadoRoute
    }
    '/painel/$encarregado/$anoMes/$dia': {
      id: '/painel/$encarregado/$anoMes/$dia'
      path: '/$anoMes/$dia'
      fullPath: '/painel/$encarregado/$anoMes/$dia'
      preLoaderRoute: typeof PainelEncarregadoAnoMesDiaRouteImport
      parentRoute: typeof PainelEncarregadoRoute
    }
  }
}

interface PainelEncarregadoRouteChildren {
  PainelEncarregadoIndexRoute: typeof PainelEncarregadoIndexRoute
  PainelEncarregadoAnoMesDiaRoute: typeof PainelEncarregadoAnoMesDiaRoute
}

const PainelEncarregadoRouteChildren: PainelEncarregadoRouteChildren = {
  PainelEncarregadoIndexRoute: PainelEncarregadoIndexRoute,
  PainelEncarregadoAnoMesDiaRoute: PainelEncarregadoAnoMesDiaRoute,
}

const PainelEncarregadoRouteWithChildren =
  PainelEncarregadoRoute._addFileChildren(PainelEncarregadoRouteChildren)

interface PainelRouteChildren {
  PainelEncarregadoRoute: typeof PainelEncarregadoRouteWithChildren
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelEncarregadoRoute: PainelEncarregadoRouteWithChildren,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
