/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as PainelVistoriasRouteImport } from './routes/painel.vistorias'
import { Route as PainelVisaoRouteImport } from './routes/painel.visao'
import { Route as PainelGuiaRouteImport } from './routes/painel.guia'
import { Route as PainelGruposRouteImport } from './routes/painel.grupos'
import { Route as PainelAiBotRouteImport } from './routes/painel.ai-bot'
import { Route as PainelAdminRouteImport } from './routes/painel.admin'
import { Route as PainelEncarregadoRouteImport } from './routes/painel.$encarregado'
import { Route as PainelVistoriasIndexRouteImport } from './routes/painel.vistorias.index'
import { Route as PainelEncarregadoIndexRouteImport } from './routes/painel.$encarregado.index'
import { Route as PainelVistoriasAdminRouteImport } from './routes/painel.vistorias.admin'
import { Route as PainelVistoriasRuaIdRouteImport } from './routes/painel.vistorias.$ruaId'
import { Route as PainelEncarregadoAnoMesDiaRouteImport } from './routes/painel.$encarregado.$anoMes.$dia'
import { Route as ApiPublicHooksUazapiBotRouteImport } from './routes/api/public/hooks/uazapi-bot'
import { Route as ApiPublicHooksProcessarRelatoriosRouteImport } from './routes/api/public/hooks/processar-relatorios'
import { Route as ApiPublicHooksProcessarAnalisesRouteImport } from './routes/api/public/hooks/processar-analises'
import { Route as ApiPublicHooksMensagensProgramadasRouteImport } from './routes/api/public/hooks/mensagens-programadas'
import { Route as ApiPublicHooksAiBotRouteImport } from './routes/api/public/hooks/ai-bot'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const PainelVistoriasRoute = PainelVistoriasRouteImport.update({
  id: '/vistorias',
  path: '/vistorias',
  getParentRoute: () => PainelRoute,
} as any)
const PainelVisaoRoute = PainelVisaoRouteImport.update({
  id: '/visao',
  path: '/visao',
  getParentRoute: () => PainelRoute,
} as any)
const PainelGuiaRoute = PainelGuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => PainelRoute,
} as any)
const PainelGruposRoute = PainelGruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAiBotRoute = PainelAiBotRouteImport.update({
  id: '/ai-bot',
  path: '/ai-bot',
  getParentRoute: () => PainelRoute,
} as any)
const PainelAdminRoute = PainelAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PainelRoute,
} as any)
const PainelEncarregadoRoute = PainelEncarregadoRouteImport.update({
  id: '/$encarregado',
  path: '/$encarregado',
  getParentRoute: () => PainelRoute,
} as any)
const PainelVistoriasIndexRoute = PainelVistoriasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelVistoriasRoute,
} as any)
const PainelEncarregadoIndexRoute = PainelEncarregadoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelEncarregadoRoute,
} as any)
const PainelVistoriasAdminRoute = PainelVistoriasAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PainelVistoriasRoute,
} as any)
const PainelVistoriasRuaIdRoute = PainelVistoriasRuaIdRouteImport.update({
  id: '/$ruaId',
  path: '/$ruaId',
  getParentRoute: () => PainelVistoriasRoute,
} as any)
const PainelEncarregadoAnoMesDiaRoute =
  PainelEncarregadoAnoMesDiaRouteImport.update({
    id: '/$anoMes/$dia',
    path: '/$anoMes/$dia',
    getParentRoute: () => PainelEncarregadoRoute,
  } as any)
const ApiPublicHooksUazapiBotRoute = ApiPublicHooksUazapiBotRouteImport.update({
  id: '/api/public/hooks/uazapi-bot',
  path: '/api/public/hooks/uazapi-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksProcessarRelatoriosRoute =
  ApiPublicHooksProcessarRelatoriosRouteImport.update({
    id: '/api/public/hooks/processar-relatorios',
    path: '/api/public/hooks/processar-relatorios',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessarAnalisesRoute =
  ApiPublicHooksProcessarAnalisesRouteImport.update({
    id: '/api/public/hooks/processar-analises',
    path: '/api/public/hooks/processar-analises',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMensagensProgramadasRoute =
  ApiPublicHooksMensagensProgramadasRouteImport.update({
    id: '/api/public/hooks/mensagens-programadas',
    path: '/api/public/hooks/mensagens-programadas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAiBotRoute = ApiPublicHooksAiBotRouteImport.update({
  id: '/api/public/hooks/ai-bot',
  path: '/api/public/hooks/ai-bot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/painel/$encarregado': typeof PainelEncarregadoRouteWithChildren
  '/painel/admin': typeof PainelAdminRoute
  '/painel/ai-bot': typeof PainelAiBotRoute
  '/painel/grupos': typeof PainelGruposRoute
  '/painel/guia': typeof PainelGuiaRoute
  '/painel/visao': typeof PainelVisaoRoute
  '/painel/vistorias': typeof PainelVistoriasRouteWithChildren
  '/painel/': typeof PainelIndexRoute
  '/painel/vistorias/$ruaId': typeof PainelVistoriasRuaIdRoute
  '/painel/vistorias/admin': typeof PainelVistoriasAdminRoute
  '/painel/$encarregado/': typeof PainelEncarregadoIndexRoute
  '/painel/vistorias/': typeof PainelVistoriasIndexRoute
  '/api/public/hooks/ai-bot': typeof ApiPublicHooksAiBotRoute
  '/api/public/hooks/mensagens-programadas': typeof ApiPublicHooksMensagensProgramadasRoute
  '/api/public/hooks/processar-analises': typeof ApiPublicHooksProcessarAnalisesRoute
  '/api/public/hooks/processar-relatorios': typeof ApiPublicHooksProcessarRelatoriosRoute
  '/api/public/hooks/uazapi-bot': typeof ApiPublicHooksUazapiBotRoute
  '/painel/$encarregado/$anoMes/$dia': typeof PainelEncarregadoAnoMesDiaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/painel/admin': typeof PainelAdminRoute
  '/painel/ai-bot': typeof PainelAiBotRoute
  '/painel/grupos': typeof PainelGruposRoute
  '/painel/guia': typeof PainelGuiaRoute
  '/painel/visao': typeof PainelVisaoRoute
  '/painel': typeof PainelIndexRoute
  '/painel/vistorias/$ruaId': typeof PainelVistoriasRuaIdRoute
  '/painel/vistorias/admin': typeof PainelVistoriasAdminRoute
  '/painel/$encarregado': typeof PainelEncarregadoIndexRoute
  '/painel/vistorias': typeof PainelVistoriasIndexRoute
  '/api/public/hooks/ai-bot': typeof ApiPublicHooksAiBotRoute
  '/api/public/hooks/mensagens-programadas': typeof ApiPublicHooksMensagensProgramadasRoute
  '/api/public/hooks/processar-analises': typeof ApiPublicHooksProcessarAnalisesRoute
  '/api/public/hooks/processar-relatorios': typeof ApiPublicHooksProcessarRelatoriosRoute
  '/api/public/hooks/uazapi-bot': typeof ApiPublicHooksUazapiBotRoute
  '/painel/$encarregado/$anoMes/$dia': typeof PainelEncarregadoAnoMesDiaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/painel/$encarregado': typeof PainelEncarregadoRouteWithChildren
  '/painel/admin': typeof PainelAdminRoute
  '/painel/ai-bot': typeof PainelAiBotRoute
  '/painel/grupos': typeof PainelGruposRoute
  '/painel/guia': typeof PainelGuiaRoute
  '/painel/visao': typeof PainelVisaoRoute
  '/painel/vistorias': typeof PainelVistoriasRouteWithChildren
  '/painel/': typeof PainelIndexRoute
  '/painel/vistorias/$ruaId': typeof PainelVistoriasRuaIdRoute
  '/painel/vistorias/admin': typeof PainelVistoriasAdminRoute
  '/painel/$encarregado/': typeof PainelEncarregadoIndexRoute
  '/painel/vistorias/': typeof PainelVistoriasIndexRoute
  '/api/public/hooks/ai-bot': typeof ApiPublicHooksAiBotRoute
  '/api/public/hooks/mensagens-programadas': typeof ApiPublicHooksMensagensProgramadasRoute
  '/api/public/hooks/processar-analises': typeof ApiPublicHooksProcessarAnalisesRoute
  '/api/public/hooks/processar-relatorios': typeof ApiPublicHooksProcessarRelatoriosRoute
  '/api/public/hooks/uazapi-bot': typeof ApiPublicHooksUazapiBotRoute
  '/painel/$encarregado/$anoMes/$dia': typeof PainelEncarregadoAnoMesDiaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/painel'
    | '/reset-password'
    | '/painel/$encarregado'
    | '/painel/admin'
    | '/painel/ai-bot'
    | '/painel/grupos'
    | '/painel/guia'
    | '/painel/visao'
    | '/painel/vistorias'
    | '/painel/'
    | '/painel/vistorias/$ruaId'
    | '/painel/vistorias/admin'
    | '/painel/$encarregado/'
    | '/painel/vistorias/'
    | '/api/public/hooks/ai-bot'
    | '/api/public/hooks/mensagens-programadas'
    | '/api/public/hooks/processar-analises'
    | '/api/public/hooks/processar-relatorios'
    | '/api/public/hooks/uazapi-bot'
    | '/painel/$encarregado/$anoMes/$dia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/painel/admin'
    | '/painel/ai-bot'
    | '/painel/grupos'
    | '/painel/guia'
    | '/painel/visao'
    | '/painel'
    | '/painel/vistorias/$ruaId'
    | '/painel/vistorias/admin'
    | '/painel/$encarregado'
    | '/painel/vistorias'
    | '/api/public/hooks/ai-bot'
    | '/api/public/hooks/mensagens-programadas'
    | '/api/public/hooks/processar-analises'
    | '/api/public/hooks/processar-relatorios'
    | '/api/public/hooks/uazapi-bot'
    | '/painel/$encarregado/$anoMes/$dia'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/painel'
    | '/reset-password'
    | '/painel/$encarregado'
    | '/painel/admin'
    | '/painel/ai-bot'
    | '/painel/grupos'
    | '/painel/guia'
    | '/painel/visao'
    | '/painel/vistorias'
    | '/painel/'
    | '/painel/vistorias/$ruaId'
    | '/painel/vistorias/admin'
    | '/painel/$encarregado/'
    | '/painel/vistorias/'
    | '/api/public/hooks/ai-bot'
    | '/api/public/hooks/mensagens-programadas'
    | '/api/public/hooks/processar-analises'
    | '/api/public/hooks/processar-relatorios'
    | '/api/public/hooks/uazapi-bot'
    | '/painel/$encarregado/$anoMes/$dia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicHooksAiBotRoute: typeof ApiPublicHooksAiBotRoute
  ApiPublicHooksMensagensProgramadasRoute: typeof ApiPublicHooksMensagensProgramadasRoute
  ApiPublicHooksProcessarAnalisesRoute: typeof ApiPublicHooksProcessarAnalisesRoute
  ApiPublicHooksProcessarRelatoriosRoute: typeof ApiPublicHooksProcessarRelatoriosRoute
  ApiPublicHooksUazapiBotRoute: typeof ApiPublicHooksUazapiBotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/vistorias': {
      id: '/painel/vistorias'
      path: '/vistorias'
      fullPath: '/painel/vistorias'
      preLoaderRoute: typeof PainelVistoriasRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/visao': {
      id: '/painel/visao'
      path: '/visao'
      fullPath: '/painel/visao'
      preLoaderRoute: typeof PainelVisaoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/guia': {
      id: '/painel/guia'
      path: '/guia'
      fullPath: '/painel/guia'
      preLoaderRoute: typeof PainelGuiaRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/grupos': {
      id: '/painel/grupos'
      path: '/grupos'
      fullPath: '/painel/grupos'
      preLoaderRoute: typeof PainelGruposRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/ai-bot': {
      id: '/painel/ai-bot'
      path: '/ai-bot'
      fullPath: '/painel/ai-bot'
      preLoaderRoute: typeof PainelAiBotRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/admin': {
      id: '/painel/admin'
      path: '/admin'
      fullPath: '/painel/admin'
      preLoaderRoute: typeof PainelAdminRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/$encarregado': {
      id: '/painel/$encarregado'
      path: '/$encarregado'
      fullPath: '/painel/$encarregado'
      preLoaderRoute: typeof PainelEncarregadoRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/vistorias/': {
      id: '/painel/vistorias/'
      path: '/'
      fullPath: '/painel/vistorias/'
      preLoaderRoute: typeof PainelVistoriasIndexRouteImport
      parentRoute: typeof PainelVistoriasRoute
    }
    '/painel/$encarregado/': {
      id: '/painel/$encarregado/'
      path: '/'
      fullPath: '/painel/$encarregado/'
      preLoaderRoute: typeof PainelEncarregadoIndexRouteImport
      parentRoute: typeof PainelEncarregadoRoute
    }
    '/painel/vistorias/admin': {
      id: '/painel/vistorias/admin'
      path: '/admin'
      fullPath: '/painel/vistorias/admin'
      preLoaderRoute: typeof PainelVistoriasAdminRouteImport
      parentRoute: typeof PainelVistoriasRoute
    }
    '/painel/vistorias/$ruaId': {
      id: '/painel/vistorias/$ruaId'
      path: '/$ruaId'
      fullPath: '/painel/vistorias/$ruaId'
      preLoaderRoute: typeof PainelVistoriasRuaIdRouteImport
      parentRoute: typeof PainelVistoriasRoute
    }
    '/painel/$encarregado/$anoMes/$dia': {
      id: '/painel/$encarregado/$anoMes/$dia'
      path: '/$anoMes/$dia'
      fullPath: '/painel/$encarregado/$anoMes/$dia'
      preLoaderRoute: typeof PainelEncarregadoAnoMesDiaRouteImport
      parentRoute: typeof PainelEncarregadoRoute
    }
    '/api/public/hooks/uazapi-bot': {
      id: '/api/public/hooks/uazapi-bot'
      path: '/api/public/hooks/uazapi-bot'
      fullPath: '/api/public/hooks/uazapi-bot'
      preLoaderRoute: typeof ApiPublicHooksUazapiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/processar-relatorios': {
      id: '/api/public/hooks/processar-relatorios'
      path: '/api/public/hooks/processar-relatorios'
      fullPath: '/api/public/hooks/processar-relatorios'
      preLoaderRoute: typeof ApiPublicHooksProcessarRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/processar-analises': {
      id: '/api/public/hooks/processar-analises'
      path: '/api/public/hooks/processar-analises'
      fullPath: '/api/public/hooks/processar-analises'
      preLoaderRoute: typeof ApiPublicHooksProcessarAnalisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mensagens-programadas': {
      id: '/api/public/hooks/mensagens-programadas'
      path: '/api/public/hooks/mensagens-programadas'
      fullPath: '/api/public/hooks/mensagens-programadas'
      preLoaderRoute: typeof ApiPublicHooksMensagensProgramadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ai-bot': {
      id: '/api/public/hooks/ai-bot'
      path: '/api/public/hooks/ai-bot'
      fullPath: '/api/public/hooks/ai-bot'
      preLoaderRoute: typeof ApiPublicHooksAiBotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PainelEncarregadoRouteChildren {
  PainelEncarregadoIndexRoute: typeof PainelEncarregadoIndexRoute
  PainelEncarregadoAnoMesDiaRoute: typeof PainelEncarregadoAnoMesDiaRoute
}

const PainelEncarregadoRouteChildren: PainelEncarregadoRouteChildren = {
  PainelEncarregadoIndexRoute: PainelEncarregadoIndexRoute,
  PainelEncarregadoAnoMesDiaRoute: PainelEncarregadoAnoMesDiaRoute,
}

const PainelEncarregadoRouteWithChildren =
  PainelEncarregadoRoute._addFileChildren(PainelEncarregadoRouteChildren)

interface PainelVistoriasRouteChildren {
  PainelVistoriasRuaIdRoute: typeof PainelVistoriasRuaIdRoute
  PainelVistoriasAdminRoute: typeof PainelVistoriasAdminRoute
  PainelVistoriasIndexRoute: typeof PainelVistoriasIndexRoute
}

const PainelVistoriasRouteChildren: PainelVistoriasRouteChildren = {
  PainelVistoriasRuaIdRoute: PainelVistoriasRuaIdRoute,
  PainelVistoriasAdminRoute: PainelVistoriasAdminRoute,
  PainelVistoriasIndexRoute: PainelVistoriasIndexRoute,
}

const PainelVistoriasRouteWithChildren = PainelVistoriasRoute._addFileChildren(
  PainelVistoriasRouteChildren,
)

interface PainelRouteChildren {
  PainelEncarregadoRoute: typeof PainelEncarregadoRouteWithChildren
  PainelAdminRoute: typeof PainelAdminRoute
  PainelAiBotRoute: typeof PainelAiBotRoute
  PainelGruposRoute: typeof PainelGruposRoute
  PainelGuiaRoute: typeof PainelGuiaRoute
  PainelVisaoRoute: typeof PainelVisaoRoute
  PainelVistoriasRoute: typeof PainelVistoriasRouteWithChildren
  PainelIndexRoute: typeof PainelIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelEncarregadoRoute: PainelEncarregadoRouteWithChildren,
  PainelAdminRoute: PainelAdminRoute,
  PainelAiBotRoute: PainelAiBotRoute,
  PainelGruposRoute: PainelGruposRoute,
  PainelGuiaRoute: PainelGuiaRoute,
  PainelVisaoRoute: PainelVisaoRoute,
  PainelVistoriasRoute: PainelVistoriasRouteWithChildren,
  PainelIndexRoute: PainelIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicHooksAiBotRoute: ApiPublicHooksAiBotRoute,
  ApiPublicHooksMensagensProgramadasRoute:
    ApiPublicHooksMensagensProgramadasRoute,
  ApiPublicHooksProcessarAnalisesRoute: ApiPublicHooksProcessarAnalisesRoute,
  ApiPublicHooksProcessarRelatoriosRoute:
    ApiPublicHooksProcessarRelatoriosRoute,
  ApiPublicHooksUazapiBotRoute: ApiPublicHooksUazapiBotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
